# 1. Identificação da Aplicação
spring.application.name=RotaTrackerAPI

# 2. Conexão com o Banco de Dados (O DataSource)
# Lembre-se de criar um banco chamado 'rotatracker' no seu pgAdmin/DBeaver antes de rodar!
spring.datasource.url=jdbc:postgresql://localhost:5432/rotatracker
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configurações do JPA / Hibernate
# Trava de segurança: O Hibernate APENAS valida as tabelas, não altera nada.
spring.jpa.hibernate.ddl-auto=validate
# Mostra no console os comandos SQL que o Java está fazendo por baixo dos panos (Ótimo para estudar!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Configuração do Flyway (Garante que ele ligue e controle o banco)
spring.flyway.enabled=true

api.security.token.secret=${JWT_SECRET:12345678}